services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DEVELOPMENT_ENV: false
      DATABASE_URL: "jdbc:postgresql://db:5432/recipeapp"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: recipeapp
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s