ktor:
#  authentication:
#    user: "testUser"
#    password: "testPassword"
  development: "$DEVELOPMENT_ENV:true"
  application:
    modules:
      - sh.deut.recipeapp.ApplicationKt.module
  deployment:
    port: "$DEPLOYMENT_PORT:8080"
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "$DATABASE_URL:jdbc:postgresql://localhost:5432/recipeapp"
  user: "$DB_USER:postgres"
  password: "$DB_PASSWORD:password"